"""
    Yourkeys Authentication API

    The authentication API exposes endpoints that are used to request a token to authenticate against the Yourkeys public APIs  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yk_auth_client
from yk_auth_client.model.add_development_user_request import AddDevelopmentUserRequest


class TestAddDevelopmentUserRequest(unittest.TestCase):
    """AddDevelopmentUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddDevelopmentUserRequest(self):
        """Test AddDevelopmentUserRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddDevelopmentUserRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
