"""
    Yourkeys Authentication API

    The authentication API exposes endpoints that are used to request a token to authenticate against the Yourkeys public APIs  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yk_auth_client
from yk_auth_client.model.set_user_units_request import SetUserUnitsRequest


class TestSetUserUnitsRequest(unittest.TestCase):
    """SetUserUnitsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSetUserUnitsRequest(self):
        """Test SetUserUnitsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SetUserUnitsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
