"""
    Yourkeys Authentication API

    The authentication API exposes endpoints that are used to request a token to authenticate against the Yourkeys public APIs  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import yk_auth_client
from yk_auth_client.api.authentication_api import AuthenticationApi  # noqa: E501


class TestAuthenticationApi(unittest.TestCase):
    """AuthenticationApi unit test stubs"""

    def setUp(self):
        self.api = AuthenticationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_authenticate_post(self):
        """Test case for api_authenticate_post

        Authenticate a user based on the supplied credentials.  # noqa: E501
        """
        pass

    def test_api_refresh_authentication_post(self):
        """Test case for api_refresh_authentication_post

        Generate a new identity token based on the supplied refresh token.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
