"""
    Yourkeys Authentication API

    The authentication API exposes endpoints that are used to request a token to authenticate against the Yourkeys public APIs  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yk_auth_client
from yk_auth_client.model.add_development_user_request import AddDevelopmentUserRequest
globals()['AddDevelopmentUserRequest'] = AddDevelopmentUserRequest
from yk_auth_client.model.add_multiple_development_users_request import AddMultipleDevelopmentUsersRequest


class TestAddMultipleDevelopmentUsersRequest(unittest.TestCase):
    """AddMultipleDevelopmentUsersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddMultipleDevelopmentUsersRequest(self):
        """Test AddMultipleDevelopmentUsersRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AddMultipleDevelopmentUsersRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
