"""
    Yourkeys Authentication API

    The authentication API exposes endpoints that are used to request a token to authenticate against the Yourkeys public APIs  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import yk_auth_client
from yk_auth_client.model.business_permission_group import BusinessPermissionGroup
from yk_auth_client.model.user_unit import UserUnit
globals()['BusinessPermissionGroup'] = BusinessPermissionGroup
globals()['UserUnit'] = UserUnit
from yk_auth_client.model.business_permission_group_development_user import BusinessPermissionGroupDevelopmentUser


class TestBusinessPermissionGroupDevelopmentUser(unittest.TestCase):
    """BusinessPermissionGroupDevelopmentUser unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBusinessPermissionGroupDevelopmentUser(self):
        """Test BusinessPermissionGroupDevelopmentUser"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BusinessPermissionGroupDevelopmentUser()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
