"""
    Yourkeys Authentication API

    The authentication API exposes endpoints that are used to request a token to authenticate against the Yourkeys public APIs  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import yk_auth_client
from yk_auth_client.api.authorization_api import AuthorizationApi  # noqa: E501


class TestAuthorizationApi(unittest.TestCase):
    """AuthorizationApi unit test stubs"""

    def setUp(self):
        self.api = AuthorizationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_authorization_add_default_business_groups_post(self):
        """Test case for api_authorization_add_default_business_groups_post

        """
        pass

    def test_api_authorization_add_development_user_post(self):
        """Test case for api_authorization_add_development_user_post

        """
        pass

    def test_api_authorization_add_development_users_post(self):
        """Test case for api_authorization_add_development_users_post

        """
        pass

    def test_api_authorization_add_group_permissions_post(self):
        """Test case for api_authorization_add_group_permissions_post

        """
        pass

    def test_api_authorization_add_group_post(self):
        """Test case for api_authorization_add_group_post

        """
        pass

    def test_api_authorization_add_user_units_post(self):
        """Test case for api_authorization_add_user_units_post

        """
        pass

    def test_api_authorization_check_user_access_get(self):
        """Test case for api_authorization_check_user_access_get

        """
        pass

    def test_api_authorization_delete_all_for_user_delete(self):
        """Test case for api_authorization_delete_all_for_user_delete

        """
        pass

    def test_api_authorization_delete_development_user_delete(self):
        """Test case for api_authorization_delete_development_user_delete

        """
        pass

    def test_api_authorization_delete_group_delete(self):
        """Test case for api_authorization_delete_group_delete

        """
        pass

    def test_api_authorization_delete_group_permissions_delete(self):
        """Test case for api_authorization_delete_group_permissions_delete

        """
        pass

    def test_api_authorization_delete_user_units_delete(self):
        """Test case for api_authorization_delete_user_units_delete

        """
        pass

    def test_api_authorization_get_permission_groups_get(self):
        """Test case for api_authorization_get_permission_groups_get

        """
        pass

    def test_api_authorization_get_permissions_get(self):
        """Test case for api_authorization_get_permissions_get

        """
        pass

    def test_api_authorization_get_user_access_get(self):
        """Test case for api_authorization_get_user_access_get

        """
        pass

    def test_api_authorization_list_all_for_development_get(self):
        """Test case for api_authorization_list_all_for_development_get

        """
        pass

    def test_api_authorization_list_all_for_user_get(self):
        """Test case for api_authorization_list_all_for_user_get

        """
        pass

    def test_api_authorization_list_all_for_users_get(self):
        """Test case for api_authorization_list_all_for_users_get

        """
        pass

    def test_api_authorization_list_units_get(self):
        """Test case for api_authorization_list_units_get

        """
        pass

    def test_api_authorization_set_development_user_group_put(self):
        """Test case for api_authorization_set_development_user_group_put

        """
        pass

    def test_api_authorization_set_group_permissions_put(self):
        """Test case for api_authorization_set_group_permissions_put

        """
        pass

    def test_api_authorization_set_user_units_put(self):
        """Test case for api_authorization_set_user_units_put

        """
        pass


if __name__ == '__main__':
    unittest.main()
