# flake8: noqa

"""
    Yourkeys Authentication API

    The authentication API exposes endpoints that are used to request a token to authenticate against the Yourkeys public APIs  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: support@yourkeys.com
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.1"

# import ApiClient
from yk_auth_client.api_client import ApiClient

# import Configuration
from yk_auth_client.configuration import Configuration

# import exceptions
from yk_auth_client.exceptions import OpenApiException
from yk_auth_client.exceptions import ApiAttributeError
from yk_auth_client.exceptions import ApiTypeError
from yk_auth_client.exceptions import ApiValueError
from yk_auth_client.exceptions import ApiKeyError
from yk_auth_client.exceptions import ApiException
